const router = require('express').Router();
const { auth, canManageMasterSchedule } = require('../middleware/auth');
const MasterSchedule = require('../models/MasterSchedule');
const Shift = require('../models/Shift');
const { differenceInCalendarDays, addDays, format, parseISO } = require('date-fns');

// Get the master schedule (single document system)
router.get('/', auth, canManageMasterSchedule, async (req, res) => {
  try {
    let schedule = await MasterSchedule.findOne().populate(
      'entries.employee',
      'name email avatar color position'
    );
    res.json(schedule);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Create or replace the master schedule
router.post('/', auth, canManageMasterSchedule, async (req, res) => {
  try {
    const { name, anchorDate } = req.body;
    await MasterSchedule.deleteMany({});
    const schedule = await MasterSchedule.create({
      name: name || 'Master Schedule',
      anchorDate,
      entries: [],
      createdBy: req.user._id,
    });
    res.status(201).json(schedule);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Update schedule name / anchorDate
router.patch('/:id', auth, canManageMasterSchedule, async (req, res) => {
  try {
    const { name, anchorDate } = req.body;
    const update = {};
    if (name !== undefined) update.name = name;
    if (anchorDate !== undefined) update.anchorDate = anchorDate;
    const schedule = await MasterSchedule.findByIdAndUpdate(req.params.id, update, { new: true });
    res.json(schedule);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Add a template entry
router.post('/:id/entries', auth, canManageMasterSchedule, async (req, res) => {
  try {
    const { week, dayOfWeek, employee, startTime, endTime, position, notes } = req.body;
    const schedule = await MasterSchedule.findByIdAndUpdate(
      req.params.id,
      {
        $push: {
          entries: { week, dayOfWeek, employee, startTime, endTime, position, notes },
        },
      },
      { new: true }
    ).populate('entries.employee', 'name email avatar color position');
    res.json(schedule);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Remove a template entry
router.delete('/:id/entries/:entryId', auth, canManageMasterSchedule, async (req, res) => {
  try {
    const schedule = await MasterSchedule.findByIdAndUpdate(
      req.params.id,
      { $pull: { entries: { _id: req.params.entryId } } },
      { new: true }
    ).populate('entries.employee', 'name email avatar color position');
    res.json(schedule);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Apply the 2-week template to the year
// Generates Shift documents from anchorDate for 365 days
router.post('/:id/apply', auth, canManageMasterSchedule, async (req, res) => {
  try {
    const { replaceExisting = false } = req.body;
    const schedule = await MasterSchedule.findById(req.params.id);
    if (!schedule) return res.status(404).json({ message: 'Master schedule not found' });
    if (!schedule.entries.length) {
      return res.status(400).json({ message: 'No template entries to apply' });
    }

    const anchor = parseISO(schedule.anchorDate);
    const endDate = addDays(anchor, 364); // 52 full weeks (364 days)

    // Build list of dates to generate
    const shiftsToCreate = [];
    let current = anchor;

    while (current <= endDate) {
      const daysSinceAnchor = differenceInCalendarDays(current, anchor);
      const cycleDay = ((daysSinceAnchor % 14) + 14) % 14; // 0-13
      const week = cycleDay < 7 ? 1 : 2;
      const dayOfWeek = current.getDay(); // 0=Sun
      const dateStr = format(current, 'yyyy-MM-dd');

      const matchingEntries = schedule.entries.filter(
        (e) => e.week === week && e.dayOfWeek === dayOfWeek
      );

      for (const entry of matchingEntries) {
        shiftsToCreate.push({
          employee: entry.employee,
          date: dateStr,
          startTime: entry.startTime,
          endTime: entry.endTime,
          position: entry.position,
          notes: entry.notes,
          status: 'scheduled',
          createdBy: req.user._id,
        });
      }

      current = addDays(current, 1);
    }

    let created = 0;
    let skipped = 0;

    if (replaceExisting) {
      // Delete all shifts in the date range that were generated by this master schedule
      const dates = [];
      let d = anchor;
      while (d <= endDate) {
        dates.push(format(d, 'yyyy-MM-dd'));
        d = addDays(d, 1);
      }
      await Shift.deleteMany({ date: { $in: dates }, createdBy: req.user._id });
      await Shift.insertMany(shiftsToCreate);
      created = shiftsToCreate.length;
    } else {
      // Insert only where no shift exists for that employee+date
      for (const shiftData of shiftsToCreate) {
        const exists = await Shift.findOne({
          employee: shiftData.employee,
          date: shiftData.date,
        });
        if (exists) {
          skipped++;
        } else {
          await Shift.create(shiftData);
          created++;
        }
      }
    }

    res.json({
      message: `Applied master schedule: ${created} shifts created, ${skipped} skipped (already scheduled).`,
      created,
      skipped,
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
